# Based on https://github.com/actions/starter-workflows/blob/main/ci/php.yml

name: PHP Composer

on:
  [ push, pull_request ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check code style
        run: composer php-cs

      - name: PHPStan check
        run: composer phpstan

      - name: Run PHPUnit tests
        run: composer run-script test
